import type { Metadata } from "next"
import "./globals.css"
import { StoreConfigProvider } from "@/context/StoreConfig.context"
import { getStoreConfig } from "@/actions/storeConfig"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const StoreConfig = await getStoreConfig()
  return (
    <html lang="en">
      <StoreConfigProvider {...StoreConfig}>
        <body className={`antialiased`}>{children}</body>
      </StoreConfigProvider>
    </html>
  )
}
